### ISSUE TITLE
Cannot find module (?) strange error

### ISSUE THREAD

**Issue by vapits** [taras42/karma-jasmine-html-reporter#21]
I try to run the tests and I'm getting this error:

>08 03 2017 15:28:40.163:ERROR [config]: Error in config file!
 { Error: Cannot find module 'karma-jasmine-html-reporter'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/vassilis/Projects/WebApp/karma.conf.js:11:7)
    at Object.parseConfig (/Users/vassilis/.nvm/versions/node/v6.9.5/lib/node_modules/karma/lib/config.js:410:5)
    at new Server (/Users/vassilis/.nvm/versions/node/v6.9.5/lib/node_modules/karma/lib/server.js:56:20)
    at Object.exports.run (/Users/vassilis/.nvm/versions/node/v6.9.5/lib/node_modules/karma/lib/cli.js:280:7)
    at Object.<anonymous> (/Users/vassilis/.nvm/versions/node/v6.9.5/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7) code: 'MODULE_NOT_FOUND' }

Though the module IS there (double & triple checked).
Here's also my conf file:

```ja
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      config: './angular-cli.json',
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

I would love some help on this.

**Comment by 27leaves** [comment]
[DELETED] ... was my fault, sorry

**Comment by vapits** [comment]
No response.

**Comment by blakekl** [comment]
@creat-or I'm running into the same problem. What did you do to fix it?

**Comment by hassan-kassim** [comment]
i just give `npm i karma-jasmine-html-reporter`  .it solves the problem .
may you need sudo.

**Comment by taruchit** [comment]
I tried to execute the below command: -
npm i karma-jasmine-html-reporter

But, then got following error: npm ERR! 407 Proxy Authorization Required: karma-jasmine-html-reporter@^0.2.2

Then, I executed-> npm install karma-jasmine-html-reporter --save-dev
But, still got the same error.

Please tell how to fix the new error and Error: Cannot find module 'karma-jasmine-html-reporter'.
